stages:
  preprocess:
    cmd: python src/preprocess.py
    deps:
      - src/preprocess.py
      - data/raw
    outs:
      - data/processed

  train:
    cmd: python src/train_models.py
    deps:
      - src/train_models.py
      - data/processed/dataset.csv
    outs:
      - models/model.joblib
      - models/vectorizer.joblib
      - models/labels.joblib